### ISSUE TITLE
Error: HTTP 422 Unprocessable Entity

### ISSUE THREAD

**Issue by doggy8088** [remy/jsonbin#13]
When I post the following data:

```
POST https://jsonbin.org/me/test

{
    "AuxAudioDevice1": {
        "deinterlace_field_order": 0,
        "deinterlace_mode": 0,
        "enabled": true,
        "flags": 0,
        "hotkeys": {
            "libobs.mute": []
        }
    }
}
```

I've got HTTP 422 response:

```
{
  "message": "Unprocessable Entity",
  "status": 422
}
```

Is that post body format wrong?

**Comment by remy** [comment]
How are you posting? Via curl or something else?

**Comment by doggy8088** [comment]
[Postman](https://www.getpostman.com/)

**Comment by remy** [comment]
Actually, I'm getting the same thing with the cli tool. I'll take a look locally.

**Comment by doggy8088** [comment]
There is a "dot" in the "libobs.mute" property.  I think that's the main point of failure.

**Comment by remy** [comment]
Yeah, that's what I suspect too.

**Comment by remy** [comment]
Just confirmed. It's mongo complaining that it can't store the key (with a period in it).

I'm taking a look if there's a work around. If you have any ideas, please do let me know too. Ta.

**Comment by remy** [comment]
Error for reference:

```
{ MongoError: The dotted field 'libobs.mute' in 'store.test.AuxAudioDevice1.hotkeys.libobs.mute' is not valid for storage.
    at Function.MongoError.create (/Users/remy/Sites/jsonbin/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (/Users/remy/Sites/jsonbin/node_modules/mongodb/lib/utils.js:114:22)
    at /Users/remy/Sites/jsonbin/node_modules/mongodb/lib/collection.js:1048:67
    at /Users/remy/Sites/jsonbin/node_modules/mongodb-core/lib/connection/pool.js:455:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by remy** [comment]
I've got a working local version that stores everything as JSON, and does a migrate on boot, but now the problem is that URLs with periods in them can't find the data:

http://localhost:3001/me/test/AuxAudioDevice1/hotkeys/libobs.mute

This converts to a path like this:

```
const value = user.store.test.AuxAudioDevice1.hotkeys.libobs.mute;
```

When it should be:

```
const value = user.store.test.AuxAudioDevice1.hotkeys['libobs.mute'];
```

Looking at fixing that too.

**Comment by remy** [comment]
Damnit, this is turning into a rabbit hole.

I've got the property saving, but I can't get it back out. It's because [undefsafe](https://github.com/remy/undefsafe) has no way to support this:

```js
const undefsafe = require('undefsafe');
const value = {
  a: { 'one.two': true }
};

const r = undefsafe(value, 'a."one.two"');
console.assert(r === true);
```

You can see way that this could work, but undefsafe doesn't support it at all right now: https://runkit.com/remy/589a024594f6ef001383cbe5

I've lost quite a bit of time on this, but if you want to take a look, I'd be happy to have another set of eyes (note that the work needs to be in https://github.com/remy/undefsafe)

**Comment by doggy8088** [comment]
Have you tried this `const r = undefsafe(value, 'a["one.two"]');`?

**Comment by remy** [comment]
Well, there's the runkit URL right there. Did you try it? What was the result?

**Comment by doggy8088** [comment]
I've got an false sadly. :-(

**Comment by doggy8088** [comment]
I read your underfsafe source code.  I think your undefsafe can't handle get property by `a['something']` format.

**Comment by remy** [comment]
That's correct.

**Comment by doggy8088** [comment]
@remy I sent a PR just minutes ago.  https://github.com/remy/undefsafe/pull/4/files

HTH.

**Comment by remy** [comment]
Just waiting my branch to appear that solves all this. Some reason github is being slow to get branches today.
