### ISSUE TITLE
Data erased over night

### ISSUE THREAD

**Issue by OrdinaryDev83** [remy/jsonbin#53]
I use this site to host data from my discord bot. However between 00:30am and 09:00am my "blog" erased and so did all my data, any particular reason why? Is it due to something i'm not aware of? (my bot was off during this period). And i'm sure it's not my bot that deleted the data.
Maybe i'm using it wrong, i'm storing the data in https://jsonbin.org/ordinarydev83/blog

**Comment by remy** [comment]
Hey there - there's nothing I can think of that would do this - but looking at the raw database records, I can see that the `blog` key still exists. It's not public - so I can't see it clicking the link above, but it's there. It's possible you've been signed out and you can't see it anymore? Otherwise you'll need to make the blog key public - you can check by visiting this url: https://jsonbin.org/_/me/public
